### PR TITLE
feat: cache manager

### PR DESCRIPTION
**Pull request by yuranevmer**
It adds to MapView methods:
- cacheCapacity()
- currentCacheUsage()
- possibleTilesInArea()
- downloadAreaAsync()
for offline usage

### CODE REVIEW

**Comment by m1ga** [comment]
Awesome :+1:  Thanks!

**Comment by m1ga** [comment]
Ah sorry, merged it too quick :-D Example is crashing with
```
[INFO]   downloadprogress 0
[ERROR] TiExceptionHandler: (main) [6327,6368] An error occurred while executing doInBackground()
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     org.osmdroid.tileprovider.cachemanager.CacheManager$3.preCheck(CacheManager.java:856)
[ERROR] TiExceptionHandler:     org.osmdroid.tileprovider.cachemanager.CacheManager$CacheManagerTask.doInBackground(CacheManager.java:749)
[ERROR] TiExceptionHandler:     org.osmdroid.tileprovider.cachemanager.CacheManager$CacheManagerTask.doInBackground(CacheManager.java:654)
[ERROR] TiExceptionHandler:     android.os.AsyncTask$3.call(AsyncTask.java:394)
[ERROR] TiExceptionHandler:     java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR] TiExceptionHandler:     android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
[ERROR] TiExceptionHandler:     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[ERROR] TiExceptionHandler:     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[ERROR] TiExceptionHandler:     java.lang.Thread.run(Thread.java:1012)
```

I'll check it unless you have a fix for that already?

**Comment by yuranevmer** [comment]
I think it is an error for unsupported to downloading mapType.
It can be fixed by changing mapType to `OSM.USGS_SAT` in example.

**Comment by m1ga** [comment]
You are right! There is an error `cacheManagerUnsupportedSource`. In USGS_SAT it will start the download

Would be great to receive that and pass it to Ti

**Comment by m1ga** [comment]
Fixed it! I've exposed `downloadAllowed` so you can check it. BUT if it was false and you switch the mapType you have to create a new Cachemanager (I set it to null).
No it is working and returning true/false if it is not allowed

**Comment by yuranevmer** [comment]
Great, thanks!

**Pull request merged**
